(* Generated by tools/tlgen from ton_api.tl. Do not edit.

   Constructor identifiers are computed from the schema text rather than
   transcribed, except where the schema pins one explicitly. *)

[@@@warning "-30-32-34-37-39"]

module R = Ton_tl.Tl.Reader
module W = Ton_tl.Tl.Writer

let bit flags n = Int32.logand flags (Int32.shift_left 1l n) <> 0l

(* A conditional field and its flag bit have to agree, or the field is
   silently dropped on the wire. Catch that here rather than at the peer. *)
let check_flag name n set present =
  if set <> present then
    invalid_arg
      (Printf.sprintf "%s.%d is %b but the field is %b" name n set present)

type tcp_pong = {
  random_id : int64;
}

and tcp_authentificate = {
  nonce : string;
}

and tcp_authentification_nonce = {
  nonce : string;
}

and tcp_authentification_complete = {
  key : public_key_union;
  signature : string;
}

and tcp_ping = {
  random_id : int64;
}

and pub_unenc = {
  data : string;
}

and pub_ed25519 = {
  key : string;
}

and pub_aes = {
  key : string;
}

and pub_overlay = {
  name : string;
}

and ton_block_id = {
  root_cell_hash : string;
  file_hash : string;
}

and ton_block_id_approve = {
  root_cell_hash : string;
  file_hash : string;
}

and public_key_union =
  | Pub_unenc of pub_unenc
  | Pub_ed25519 of pub_ed25519
  | Pub_aes of pub_aes
  | Pub_overlay of pub_overlay

and tcp_message_union =
  | Tcp_authentificate of tcp_authentificate
  | Tcp_authentification_nonce of tcp_authentification_nonce
  | Tcp_authentification_complete of tcp_authentification_complete

and ton_block_id_union =
  | Ton_block_id of ton_block_id
  | Approve of ton_block_id_approve

(* tcp.pong random_id:long = tcp.Pong; *)
let tcp_pong_id = 0xdc69fb03l

(* tcp.authentificate nonce:bytes = tcp.Message; *)
let tcp_authentificate_id = 0x445bab12l

(* tcp.authentificationNonce nonce:bytes = tcp.Message; *)
let tcp_authentification_nonce_id = 0xe35d4ab6l

(* tcp.authentificationComplete key:PublicKey signature:bytes = tcp.Message; *)
let tcp_authentification_complete_id = 0xf7ad9ea6l

(* tcp.ping random_id:long = tcp.Pong; *)
let tcp_ping_id = 0x4d082b9al

(* pub.unenc data:bytes = PublicKey; *)
let pub_unenc_id = 0xb61f450al

(* pub.ed25519 key:int256 = PublicKey; *)
let pub_ed25519_id = 0x4813b4c6l

(* pub.aes key:int256 = PublicKey; *)
let pub_aes_id = 0x2dbcadd4l

(* pub.overlay name:bytes = PublicKey; *)
let pub_overlay_id = 0x34ba45cbl

(* ton.blockId root_cell_hash:int256 file_hash:int256 = ton.BlockId; *)
let ton_block_id_id = 0xc50b6e70l

(* ton.blockIdApprove root_cell_hash:int256 file_hash:int256 = ton.BlockId; *)
let ton_block_id_approve_id = 0x2dd44a49l

let rec read_tcp_pong r : tcp_pong =
  let random_id = R.long r in
  { random_id }

and write_tcp_pong w (v : tcp_pong) =
  let random_id = v.random_id in
  W.long w random_id;
  ()

and read_boxed_tcp_pong r : tcp_pong = R.expect r tcp_pong_id; read_tcp_pong r

and write_boxed_tcp_pong w v = W.constructor w tcp_pong_id; write_tcp_pong w v

and read_tcp_authentificate r : tcp_authentificate =
  let nonce = R.bytes r in
  { nonce }

and write_tcp_authentificate w (v : tcp_authentificate) =
  let nonce = v.nonce in
  W.bytes w nonce;
  ()

and read_boxed_tcp_authentificate r : tcp_authentificate = R.expect r tcp_authentificate_id; read_tcp_authentificate r

and write_boxed_tcp_authentificate w v = W.constructor w tcp_authentificate_id; write_tcp_authentificate w v

and read_tcp_authentification_nonce r : tcp_authentification_nonce =
  let nonce = R.bytes r in
  { nonce }

and write_tcp_authentification_nonce w (v : tcp_authentification_nonce) =
  let nonce = v.nonce in
  W.bytes w nonce;
  ()

and read_boxed_tcp_authentification_nonce r : tcp_authentification_nonce = R.expect r tcp_authentification_nonce_id; read_tcp_authentification_nonce r

and write_boxed_tcp_authentification_nonce w v = W.constructor w tcp_authentification_nonce_id; write_tcp_authentification_nonce w v

and read_tcp_authentification_complete r : tcp_authentification_complete =
  let key = read_union_public_key r in
  let signature = R.bytes r in
  { key; signature }

and write_tcp_authentification_complete w (v : tcp_authentification_complete) =
  let key = v.key in
  let signature = v.signature in
  write_union_public_key w key;
  W.bytes w signature;
  ()

and read_boxed_tcp_authentification_complete r : tcp_authentification_complete = R.expect r tcp_authentification_complete_id; read_tcp_authentification_complete r

and write_boxed_tcp_authentification_complete w v = W.constructor w tcp_authentification_complete_id; write_tcp_authentification_complete w v

and read_tcp_ping r : tcp_ping =
  let random_id = R.long r in
  { random_id }

and write_tcp_ping w (v : tcp_ping) =
  let random_id = v.random_id in
  W.long w random_id;
  ()

and read_boxed_tcp_ping r : tcp_ping = R.expect r tcp_ping_id; read_tcp_ping r

and write_boxed_tcp_ping w v = W.constructor w tcp_ping_id; write_tcp_ping w v

and read_pub_unenc r : pub_unenc =
  let data = R.bytes r in
  { data }

and write_pub_unenc w (v : pub_unenc) =
  let data = v.data in
  W.bytes w data;
  ()

and read_boxed_pub_unenc r : pub_unenc = R.expect r pub_unenc_id; read_pub_unenc r

and write_boxed_pub_unenc w v = W.constructor w pub_unenc_id; write_pub_unenc w v

and read_pub_ed25519 r : pub_ed25519 =
  let key = R.int256 r in
  { key }

and write_pub_ed25519 w (v : pub_ed25519) =
  let key = v.key in
  W.int256 w key;
  ()

and read_boxed_pub_ed25519 r : pub_ed25519 = R.expect r pub_ed25519_id; read_pub_ed25519 r

and write_boxed_pub_ed25519 w v = W.constructor w pub_ed25519_id; write_pub_ed25519 w v

and read_pub_aes r : pub_aes =
  let key = R.int256 r in
  { key }

and write_pub_aes w (v : pub_aes) =
  let key = v.key in
  W.int256 w key;
  ()

and read_boxed_pub_aes r : pub_aes = R.expect r pub_aes_id; read_pub_aes r

and write_boxed_pub_aes w v = W.constructor w pub_aes_id; write_pub_aes w v

and read_pub_overlay r : pub_overlay =
  let name = R.bytes r in
  { name }

and write_pub_overlay w (v : pub_overlay) =
  let name = v.name in
  W.bytes w name;
  ()

and read_boxed_pub_overlay r : pub_overlay = R.expect r pub_overlay_id; read_pub_overlay r

and write_boxed_pub_overlay w v = W.constructor w pub_overlay_id; write_pub_overlay w v

and read_ton_block_id r : ton_block_id =
  let root_cell_hash = R.int256 r in
  let file_hash = R.int256 r in
  { root_cell_hash; file_hash }

and write_ton_block_id w (v : ton_block_id) =
  let root_cell_hash = v.root_cell_hash in
  let file_hash = v.file_hash in
  W.int256 w root_cell_hash;
  W.int256 w file_hash;
  ()

and read_boxed_ton_block_id r : ton_block_id = R.expect r ton_block_id_id; read_ton_block_id r

and write_boxed_ton_block_id w v = W.constructor w ton_block_id_id; write_ton_block_id w v

and read_ton_block_id_approve r : ton_block_id_approve =
  let root_cell_hash = R.int256 r in
  let file_hash = R.int256 r in
  { root_cell_hash; file_hash }

and write_ton_block_id_approve w (v : ton_block_id_approve) =
  let root_cell_hash = v.root_cell_hash in
  let file_hash = v.file_hash in
  W.int256 w root_cell_hash;
  W.int256 w file_hash;
  ()

and read_boxed_ton_block_id_approve r : ton_block_id_approve = R.expect r ton_block_id_approve_id; read_ton_block_id_approve r

and write_boxed_ton_block_id_approve w v = W.constructor w ton_block_id_approve_id; write_ton_block_id_approve w v

and read_union_public_key r : public_key_union =
  let id = R.constructor r in
  if id = pub_unenc_id then Pub_unenc (read_pub_unenc r)
  else if id = pub_ed25519_id then Pub_ed25519 (read_pub_ed25519 r)
  else if id = pub_aes_id then Pub_aes (read_pub_aes r)
  else if id = pub_overlay_id then Pub_overlay (read_pub_overlay r)
  else R.fail (R.Message (Printf.sprintf "unexpected constructor %08lx for PublicKey" id))

and write_union_public_key w = function
  | Pub_unenc v -> W.constructor w pub_unenc_id; write_pub_unenc w v
  | Pub_ed25519 v -> W.constructor w pub_ed25519_id; write_pub_ed25519 w v
  | Pub_aes v -> W.constructor w pub_aes_id; write_pub_aes w v
  | Pub_overlay v -> W.constructor w pub_overlay_id; write_pub_overlay w v

and read_union_tcp_message r : tcp_message_union =
  let id = R.constructor r in
  if id = tcp_authentificate_id then Tcp_authentificate (read_tcp_authentificate r)
  else if id = tcp_authentification_nonce_id then Tcp_authentification_nonce (read_tcp_authentification_nonce r)
  else if id = tcp_authentification_complete_id then Tcp_authentification_complete (read_tcp_authentification_complete r)
  else R.fail (R.Message (Printf.sprintf "unexpected constructor %08lx for tcp.Message" id))

and write_union_tcp_message w = function
  | Tcp_authentificate v -> W.constructor w tcp_authentificate_id; write_tcp_authentificate w v
  | Tcp_authentification_nonce v -> W.constructor w tcp_authentification_nonce_id; write_tcp_authentification_nonce w v
  | Tcp_authentification_complete v -> W.constructor w tcp_authentification_complete_id; write_tcp_authentification_complete w v

and read_union_ton_block_id r : ton_block_id_union =
  let id = R.constructor r in
  if id = ton_block_id_id then Ton_block_id (read_ton_block_id r)
  else if id = ton_block_id_approve_id then Approve (read_ton_block_id_approve r)
  else R.fail (R.Message (Printf.sprintf "unexpected constructor %08lx for ton.BlockId" id))

and write_union_ton_block_id w = function
  | Ton_block_id v -> W.constructor w ton_block_id_id; write_ton_block_id w v
  | Approve v -> W.constructor w ton_block_id_approve_id; write_ton_block_id_approve w v

