open Ton_cell

let hex s =
  String.concat "" (List.init (String.length s) (fun i -> Printf.sprintf "%02x" (Char.code s.[i])))

let read_file p =
  let ic = open_in_bin p in
  let n = in_channel_length ic in
  let s = really_input_string ic n in
  close_in ic;
  s

(* The .txt fixtures are base64; veryLarge.boc is raw. *)
let load name =
  let raw = read_file ("../vectors/ton-core/" ^ name) in
  if String.length raw > 3 && String.sub raw 0 3 = "te6" then
    let stripped = String.concat "" (String.split_on_char '\n' raw |> List.map String.trim) in
    match Base64.decode stripped with
    | Ok s -> s
    | Error (`Msg m) -> Alcotest.failf "%s: bad base64: %s" name m
  else raw

let fixtures =
  [ "accountProof.txt"; "accountState.txt"; "accountStateTest.txt";
    "accountStateTestPruned.txt"; "block.txt"; "block2.txt"; "configProof.txt";
    "largeBoc.txt"; "manyCells.txt"; "veryLarge.boc" ]

let ok name = function Ok v -> v | Error e -> Alcotest.failf "%s: %a" name Boc.pp_error e

(* --- differential test against the reference implementation --------------- *)

(* The fixtures were produced by the C++ node, and the reference TypeScript SDK
   does not re-serialize them byte-for-byte either -- it makes different
   ordering and width choices. So "correct" cannot mean "reproduces the input";
   it means "agrees with the reference". These expectations are generated by
   tools/gen-vectors and committed, so the suite stays offline. *)

let expected =
  lazy
    (match Yojson.Safe.from_string (read_file "../vectors/ton-core-expected.json") with
    | `Assoc l -> l
    | _ -> Alcotest.fail "ton-core-expected.json: expected an object")

let field name obj =
  match List.assoc_opt name obj with
  | Some v -> v
  | None -> Alcotest.failf "missing field %S" name

let to_int = function `Int n -> n | _ -> Alcotest.fail "expected an int"
let to_str = function `String s -> s | _ -> Alcotest.fail "expected a string"
let to_obj = function `Assoc l -> l | _ -> Alcotest.fail "expected an object"
let to_list = function `List l -> l | _ -> Alcotest.fail "expected a list"
let sha256 s = hex Digestif.SHA256.(to_raw_string (digest_string s))

let identity_count root =
  let seen = Hashtbl.create 64 in
  let rec go c =
    let h = Cell.identity c in
    if not (Hashtbl.mem seen h) then begin
      Hashtbl.add seen h ();
      List.iter go (Cell.refs c)
    end
  in
  go root;
  Hashtbl.length seen

let test_vs_reference name () =
  let spec = to_obj (field name (Lazy.force expected)) in
  let roots = ok name (Boc.deserialize (load name)) in
  let want_roots = to_list (field "roots" spec) in
  Alcotest.(check int) (name ^ ": root count") (List.length want_roots) (List.length roots);
  List.iteri
    (fun i (root, want) ->
      let want = to_obj want in
      let at f = Printf.sprintf "%s root[%d] %s" name i f in
      (* hash0 is the representation hash; hash3 is the cell identity. They
         differ exactly when the root is a leveled/exotic cell. *)
      Alcotest.(check string) (at "hash0") (to_str (field "hash0" want)) (hex (Cell.hash ~level:0 root));
      Alcotest.(check string) (at "hash3") (to_str (field "hash3" want)) (hex (Cell.hash ~level:3 root));
      Alcotest.(check string) (at "identity") (to_str (field "hash3" want)) (hex (Cell.identity root));
      Alcotest.(check int) (at "depth") (to_int (field "depth0" want)) (Cell.depth ~level:0 root);
      Alcotest.(check int) (at "level") (to_int (field "level" want)) (Cell.level root);
      Alcotest.(check int) (at "cell count") (to_int (field "cells" want)) (identity_count root))
    (List.combine roots want_roots);
  (* Byte-level agreement: our encoder must emit exactly what the reference
     emits, for every combination of the two optional container fields. *)
  match (roots, List.assoc_opt "reserialized" spec) with
  | [ root ], Some re ->
      List.iter
        (fun (idx, crc32) ->
          let key = Printf.sprintf "idx=%b,crc32=%b" idx crc32 in
          let want = to_obj (field key (to_obj re)) in
          let out = Boc.serialize ~idx ~crc32 root in
          Alcotest.(check int)
            (Printf.sprintf "%s %s length" name key)
            (to_int (field "len" want)) (String.length out);
          Alcotest.(check string)
            (Printf.sprintf "%s %s bytes" name key)
            (to_str (field "sha256" want)) (sha256 out))
        [ (false, false); (true, false); (false, true); (true, true) ]
  | _ -> ()

(* Independent of what the reference produces: whatever we encode, we must be
   able to decode back to the same DAG. *)
let test_reencode name () =
  match Boc.deserialize (load name) with
  | Ok [ root ] ->
      List.iter
        (fun (idx, crc32) ->
          let back = ok name (Boc.deserialize_root (Boc.serialize ~idx ~crc32 root)) in
          Alcotest.(check string)
            (Printf.sprintf "%s idx=%b crc=%b" name idx crc32)
            (hex (Cell.identity root)) (hex (Cell.identity back)))
        [ (false, false); (true, false); (false, true); (true, true) ]
  | Ok _ -> ()
  | Error e -> Alcotest.failf "%s: %a" name Boc.pp_error e

(* The proofs are the fixtures that matter most: they carry pruned branches at
   several levels, so parsing them at all means the level-mask and
   higher-hash logic agrees with the reference implementation. *)
let test_proofs_are_exotic () =
  let survey root =
    let seen = Hashtbl.create 64 in
    let n = ref 0 and levels = ref 0 in
    let rec go c =
      let h = Cell.identity c in
      if not (Hashtbl.mem seen h) then begin
        Hashtbl.add seen h ();
        if Cell.is_exotic c then incr n;
        levels := max !levels (Cell.level c);
        List.iter go (Cell.refs c)
      end
    in
    go root;
    (!n, !levels)
  in
  List.iter
    (fun name ->
      match Boc.deserialize (load name) with
      | Ok (root :: _) ->
          let n, levels = survey root in
          Alcotest.(check bool) (name ^ ": contains exotic cells") true (n > 0);
          Alcotest.(check bool) (name ^ ": reaches level >= 1") true (levels >= 1)
      | _ -> Alcotest.failf "%s: expected a root" name)
    [ "accountProof.txt"; "configProof.txt"; "accountStateTestPruned.txt" ]

(* --- malformed input ------------------------------------------------------ *)

let rejects name src expected =
  Alcotest.test_case name `Quick (fun () ->
      match Boc.deserialize src with
      | Ok _ -> Alcotest.failf "accepted malformed input"
      | Error e -> Alcotest.(check string) "error" expected (Format.asprintf "%a" Boc.pp_error e))

let test_malformed =
  let good = lazy (load "accountStateTestPruned.txt") in
  [ rejects "empty input" "" "truncated while reading magic: want 4 bytes, have 0";
    rejects "bad magic" "\x00\x00\x00\x00" "not a bag of cells: magic 0x00000000";
    Alcotest.test_case "truncated body" `Quick (fun () ->
        let s = Lazy.force good in
        match Boc.deserialize (String.sub s 0 (String.length s / 2)) with
        | Ok _ -> Alcotest.fail "accepted a truncated bag of cells"
        | Error _ -> ());
    Alcotest.test_case "corrupted crc is detected" `Quick (fun () ->
        let s = Boc.serialize ~crc32:true Cell.empty in
        let b = Bytes.of_string s in
        let i = Bytes.length b - 1 in
        Bytes.set b i (Char.chr (Char.code (Bytes.get b i) lxor 0xff));
        match Boc.deserialize (Bytes.to_string b) with
        | Ok _ -> Alcotest.fail "accepted a bag of cells with a broken checksum"
        | Error (Boc.Bad_crc _) -> ()
        | Error e -> Alcotest.failf "wrong error: %a" Boc.pp_error e);
    Alcotest.test_case "flipping a data byte changes the root hash" `Quick (fun () ->
        let s = Lazy.force good in
        let root = ok "pruned" (Boc.deserialize_root s) in
        let b = Bytes.of_string s in
        let i = Bytes.length b - 3 in
        Bytes.set b i (Char.chr (Char.code (Bytes.get b i) lxor 0x01));
        match Boc.deserialize_root (Bytes.to_string b) with
        | Ok other ->
            Alcotest.(check bool) "hash must differ" false (String.equal (Cell.hash root) (Cell.hash other))
        | Error _ -> () (* rejecting outright is also fine *)) ]

(* --- synthetic ------------------------------------------------------------ *)

let test_empty_cell_boc () =
  let back = ok "empty" (Boc.deserialize_root (Boc.serialize Cell.empty)) in
  Alcotest.(check string) "empty cell survives" (hex (Cell.hash Cell.empty)) (hex (Cell.hash back))

(* Two identical subtrees must be stored once, so the cell count is lower than
   a naive traversal would suggest. *)
let test_dedup () =
  let leaf = Result.get_ok (Cell.make ~exotic:false (Bits.of_bytes "\x42") []) in
  let root = Result.get_ok (Cell.make ~exotic:false Bits.empty [ leaf; leaf; leaf ]) in
  Alcotest.(check int) "deduplicated to root + leaf" 2 (List.length (Boc.topological_sort root));
  let back = ok "dedup" (Boc.deserialize_root (Boc.serialize root)) in
  Alcotest.(check string) "hash preserved" (hex (Cell.hash root)) (hex (Cell.hash back));
  Alcotest.(check int) "still three refs" 3 (Cell.ref_count back)

(* Every reference must point strictly forward, which is what makes the
   back-to-front build in the decoder sound. *)
let test_ordering () =
  let a = Result.get_ok (Cell.make ~exotic:false (Bits.of_bytes "\x01") []) in
  let b = Result.get_ok (Cell.make ~exotic:false (Bits.of_bytes "\x02") [ a ]) in
  let root = Result.get_ok (Cell.make ~exotic:false Bits.empty [ b; a ]) in
  List.iteri
    (fun i (_, refs) ->
      List.iter
        (fun r -> Alcotest.(check bool) (Printf.sprintf "cell %d -> %d is forward" i r) true (r > i))
        refs)
    (Boc.topological_sort root)

let () =
  Alcotest.run "boc"
    [ ( "vs reference",
        List.map (fun n -> Alcotest.test_case n `Quick (test_vs_reference n)) fixtures );
      ("re-encode", List.map (fun n -> Alcotest.test_case n `Quick (test_reencode n)) fixtures);
      ("proofs", [ Alcotest.test_case "proof fixtures carry exotic cells" `Quick test_proofs_are_exotic ]);
      ("malformed", test_malformed);
      ( "synthetic",
        [ Alcotest.test_case "empty cell" `Quick test_empty_cell_boc;
          Alcotest.test_case "deduplication" `Quick test_dedup;
          Alcotest.test_case "reference ordering" `Quick test_ordering ] )
    ]
